apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shepherd-pv-claim
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: shepherd
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: shepherd-pv-storage
              persistentVolumeClaim:
                claimName: shepherd-pv-claim
          containers:
          - name: shepherd
            image: willat8/shepherd
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: "/home/shepherd/.shepherd/output.xmltv"
                name: shepherd-pv-storage
                subPath: output.xmltv
              - mountPath: "/home/shepherd/.shepherd/shepherd.conf"
                name: shepherd-pv-storage
                subPath: shepherd.conf
          initContainers:
          - name: init-shepherd
            image: willat8/shepherd
            imagePullPolicy: Always
            volumeMounts:
              - mountPath: "/home/shepherd/pv"
                name: shepherd-pv-storage
            command:
              - "/bin/sh"
              - "-c"
              - "touch /home/shepherd/pv/output.xmltv && cp -n /home/shepherd/.shepherd/shepherd.conf /home/shepherd/pv/shepherd.conf"
          restartPolicy: Never

