#!/bin/bash

curl -LO https://github.com/multiarch/qemu-user-static/releases/download/v6.1.0-5/qemu-aarch64-static
chmod +x qemu-aarch64-static
docker run --rm --privileged multiarch/qemu-user-static:register --reset

docker buildx create --use --name arm64-builder --driver docker
docker buildx build --platform linux/arm64 -f "${DOCKERFILE_PATH:-Dockerfile}" -t "$IMAGE_NAME" .
docker buildx build --platform linux/amd64 --output "type=image,name=${DOCKER_REPO},push-by-digest=true,push=true" --iidfile iid.txt -f "${DOCKERFILE_PATH:-Dockerfile}" .

