#!/bin/bash

# As per https://docs.docker.com/engine/reference/commandline/buildx_build/#allow
#docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'
#docker buildx build --allow security.insecure --load --platform linux/arm64 -f "${DOCKERFILE_PATH:-Dockerfile}" -t "$IMAGE_NAME" .
docker context ls
docker buildx create --use --name insecure-builder --platform linux/arm64 --driver docker-container
docker buildx build --load --platform linux/arm64 -f "${DOCKERFILE_PATH:-Dockerfile}" -t "$IMAGE_NAME" .

