#!/bin/bash

wget https://github.com/multiarch/qemu-user-static/releases/download/v6.1.0-5/qemu-aarch64-static

# As per https://docs.docker.com/engine/reference/commandline/buildx_build/#allow
#docker buildx create --use --name insecure-builder --buildkitd-flags '--allow-insecure-entitlement security.insecure'
#docker buildx build --allow security.insecure --load --platform linux/arm64 -f "${DOCKERFILE_PATH:-Dockerfile}" -t "$IMAGE_NAME" .
docker run --rm --privileged multiarch/qemu-user-static:register --reset
#docker buildx create --use --name insecure-builder --platform linux/arm64 --driver docker-container
docker buildx build --load --platform linux/arm64 -f "${DOCKERFILE_PATH:-Dockerfile}" -t "$IMAGE_NAME" .

